### ISSUE TITLE
put some default code in each index.js root file (app and src) so the server can start

### ISSUE THREAD

**Issue by scamden** [relateiq/bedrock#7]

**Comment by joechrz** [comment]
server starts when the files are empty (this may have been some other underlying issue like a missing `release/` folder or something)

**Comment by scamden** [comment]
Hmm ok, when I added those files it started so not sure
Sent from RelateIQ2
sig

On November 3, 2015 at 11:22 AMJoe Chrzanowski<notifications@github.com>
wrote:

server starts when the files are empty (this may have been some other
underlying issue like a missing release/ folder or something)

—
Reply to this email directly or view it on GitHub
<https://github.com/relateiq/bedrock/issues/7#issuecomment-153460880>.
